package Modelo;
// Generated 17-nov-2021 18:19:02 by Hibernate Tools 4.3.1



/**
 * Profesor generated by hbm2java
 */
public class Profesor  implements java.io.Serializable {


     private long id;
     private String nombre;

    public Profesor() {
    }

	
    public Profesor(long id) {
        this.id = id;
    }
    public Profesor(long id, String nombre) {
       this.id = id;
       this.nombre = nombre;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


