package Modelo;
// Generated 17-nov-2021 19:48:26 by Hibernate Tools 4.3.1



/**
 * Libro generated by hbm2java
 */
public class Libro  implements java.io.Serializable {


     private String id;
     private Persona persona;
     private String titulo;

    public Libro() {
    }

	
    public Libro(String id) {
        this.id = id;
    }
    public Libro(String id, Persona persona, String titulo) {
       this.id = id;
       this.persona = persona;
       this.titulo = titulo;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    @Override
    public String toString() {
        return "Codigo: "+ this.id + " nombre: " + this.titulo;
    }




}


