package Modelo;
// Generated 17-nov-2021 19:48:26 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private long idpersona;
     private String nombre;
     private Set libros = new HashSet(0);

    public Persona() {
    }

	
    public Persona(long idpersona) {
        this.idpersona = idpersona;
    }
    public Persona(long idpersona, String nombre, Set libros) {
       this.idpersona = idpersona;
       this.nombre = nombre;
       this.libros = libros;
    }
   
    public long getIdpersona() {
        return this.idpersona;
    }
    
    public void setIdpersona(long idpersona) {
        this.idpersona = idpersona;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getLibros() {
        return this.libros;
    }
    
    public void setLibros(Set libros) {
        this.libros = libros;
    }
    public int numLibros(){
        return this.libros.size();
    }
    @Override
    public String toString() {
        return "Persona{" + "nombre=" + nombre + '}';
    }




}


